### ISSUE TITLE
 无限报错,报错片段如下

### ISSUE THREAD

**Issue by xiaofengv233** [buiawpkgew1/FN-FAL-s-Amplifications-zh#137]
**Describe the bug**

**To Reproduce (Important)**

**Expected behavior**

**Screenshots**

**Server Log**

**Environment (REQUIRED)**

 - Server Software and Version (Spigot/Paper):
 - Minecraft version:1.20.1
 - Slimefun version:Slimefun-230827-a00a1e3-Insider
 - FNAmplification version:最新

无限报错,报错片段如下
[临时记录.txt](https://github.com/buiawpkgew1/FN-FAL-s-Amplifications-zh/files/12532366/default.txt)

**Comment by buiawpkgew1** [comment]
https://github.com/buiawpkgew1/FN-FAL-s-Amplifications-zh/pull/135
1.20+目前没有合并，在学校军训

**Comment by xiaofengv233** [comment]
> #135 1.20+目前没有合并，在学校军训

好的😂大佬加油

**Comment by buiawpkgew1** [comment]
> > #135 1.20+目前没有合并，在学校军训
> 
> 好的😂大佬加油

刚刚发手机，一会还收手机😂😂
