### ISSUE TITLE
If you need help, contact me on discord 

### ISSUE THREAD

**Issue by FN-FAL113** [buiawpkgew1/FN-FAL-s-Amplifications-zh#14]
FN_FAL#7779
or in the sf addon community in fn ampli channel

**Comment by buiawpkgew1** [comment]
Do you have a telegram?

**Comment by FN-FAL113** [comment]
I do but I don't use it anymore, used it once long time ago

**Comment by FN-FAL113** [comment]
The code has been rewritten and cleaned up many times, it might be the cause for your failing build. You can refactor some changes to your current translation to reflect the changes
