### ISSUE TITLE
请求允许接入鬼斩构建站及slimefun Addon界面（如果可以持续保持更新）

### ISSUE THREAD

**Issue by haiman233** [buiawpkgew1/FN-FAL-s-Amplifications-zh#3]
您好buiawpkgew1，我是粘液中文wiki addon界面维护者兼汉化人员 haiman，很高兴能看到有新的面孔能接手粘液科技FN科技附属汉化工作，如果您想成为粘液科技汉化工作者的一员，可以联系我及鬼斩（ybw0014），我将会在粘液科技wiki里注明您的名字，如果您可以保证接手并持续更新FN科技汉化版，我将会在下次wiki更新中添加您的链接，并接入构建库（详见https://github.com/ybw0014/maven-builds）
您可以直接在这条issue下回复任何相关信息
也可加我的qq：2906266394
粘液科技汉化版qq群： 807302496

**Comment by buiawpkgew1** [comment]
@haiman233 我这个是机翻的

**Comment by haiman233** [comment]
这个没问题，您汉化完以后，我们可以帮助您对物品描述进行更合乎其意的修改

**Comment by haiman233** [comment]
接入构建库我可以帮您接入

**Comment by buiawpkgew1** [comment]
好的

**Comment by buiawpkgew1** [comment]
@haiman233 请问自动更新是不是这样的 https://github.com/buiawpkgew1/FN-FAL-s-Amplifications-zh/blob/90ad8bac9358ee284528540faed0aff874ebd354/src/main/java/ne/fnfal113/fnamplifications/FNAmplifications.java#L62

**Comment by buiawpkgew1** [comment]
> 这个没问题，您汉化完以后，我们可以帮助您对物品描述进行更合乎其意的修改

@haiman233 请问自动更新是不是这样的 https://github.com/buiawpkgew1/FN-FAL-s-Amplifications-zh/blob/90ad8bac9358ee284528540faed0aff874ebd354/src/main/java/ne/fnfal113/fnamplifications/FNAmplifications.java#L62

**Comment by ybw0014** [comment]
https://github.com/ybw0014/maven-builds#%E6%B7%BB%E5%8A%A0%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%96%B0%E7%B1%BB
不是`GithubBuildsUpdater`而是`GuizhanBuildsUpdater`

**Comment by buiawpkgew1** [comment]
> [ybw0014/maven-builds#%E6%B7%BB%E5%8A%A0%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%96%B0%E7%B1%BB](https://github.com/ybw0014/maven-builds#%E6%B7%BB%E5%8A%A0%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%96%B0%E7%B1%BB) 不是`GithubBuildsUpdater`而是`GuizhanBuildsUpdater`

是不是https://github.com/buiawpkgew1/FN-FAL-s-Amplifications-zh/blob/90ad8bac9358ee284528540faed0aff874ebd354/src/main/java/ne/fnfal113/fnamplifications/FNAmplifications.java#L6

**Comment by ybw0014** [comment]
```java
import net.guizhanss.guizhanlib.updater.GuizhanBuildsUpdater;
```

```java
		if (cfg.getBoolean("options.auto-update") &&
            getDescription().getVersion().startsWith("Build ")) {
            new GuizhanBuildsUpdater(this, getFile(), "用户名", "仓库", "分支", false).start();
        }
```

**Comment by buiawpkgew1** [comment]
哦

**Comment by buiawpkgew1** [comment]
![image](https://user-images.githubusercontent.com/71136405/154826955-dff642f0-9546-4077-8752-4b97f6ca4fef.png)
![image](https://user-images.githubusercontent.com/71136405/154826965-304cb17b-1690-40c0-b5c1-95cd2ff2cb45.png)
![image](https://user-images.githubusercontent.com/71136405/154826969-56020e39-9420-4e03-9df8-adea7f2efcb6.png)

**Comment by ybw0014** [comment]
上面更新了

**Comment by buiawpkgew1** [comment]
哪上面

**Comment by ybw0014** [comment]
> ```java
> import net.guizhanss.guizhanlib.updater.GuizhanBuildsUpdater;
> ```
> 
> ```java
>         if (getConfig().getBoolean("auto-update") &&
>             getDescription().getVersion().startsWith("Build ")) {
>             new GuizhanBuildsUpdater(this, getFile(), "用户名", "仓库", "分支", false).start();
>         }
> ```

**Comment by buiawpkgew1** [comment]
@ybw0014 1.18.1
![image](https://user-images.githubusercontent.com/71136405/154828102-4c3ce942-ec5d-498c-8ff3-e37e33ec02e1.png)

**Comment by ybw0014** [comment]
pom.xml里面有两个shade plugin, 合并配置保留一个
